apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - datasourceName: Tempo
          datasourceUid: Tempo
          matcherRegex: trace_id=([a-zA-Z0-9]+)
          name: trace_id
          url: $${__value.raw}

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false