server:
  http_listen_port: 9080
  grpc_listen_port: 9095

clients:
  - url: http://loki:3100/loki/api/v1/push  # Push logs to Loki via the service name (loki) in the Docker network

positions:
  filename: /tmp/positions.yaml  # Location for storing log position

scrape_configs:
  - job_name: 'dao-service'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'dao-service'
          __path__: /app/dao-service/logs/*.log
