stream_over_http_enabled: true

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 24h

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095 # required for localblocks processor

query_frontend:
  search:
    duration_slo: 5s

metrics_generator:
  processor:
    service_graphs:
      wait: 10s
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  ingestion_rate_limit_bytes: 150000000
  ingestion_burst_size_bytes: 200000000
  max_bytes_per_trace: 50000000
  metrics_generator_processors:
    - service-graphs
    - span-metrics
