services:
  web3-proxy-service:
    container_name: web3_proxy
    build:
      context: ./
      args:
        - APP_ENV=${APP_ENV}
    ports:
      - 3004:3000
    volumes:
      - ./artifacts:/app/artifacts
      - ./src:/app/src # Only sync source code
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./logs:/app/logs
      
    env_file:
      - .env
    networks:
      - fincube23_network

networks:
  fincube23_network:
    external: true
