version: '3'

services:
  filebeat:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml   # Mount filebeat.yml
      - /dao-service/logs:/logs/dao-service                         # Mount dao-service logs
    networks:
      - fincube23_network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - fincube23_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - fincube23_network

networks:
  fincube23_network:
    external: true
