services:
  audit-app:
    container_name: audit_service_api
    build:
      context: ./
      args:
        - APP_ENV
    command: npm run start
    ports:
      - 3003:3000
    volumes:
      - ./:/usr/src/app
      # - node_modules:/usr/src/app/node_modules/
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      DB_HOST: postgres-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    env_file:  # Add this line to specify the environment file
      - .env  # Specify the path to your .env file

  pgsqldb:
    container_name: pgsqldb
    image: postgres:16
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      - pgsqldb

volumes:
  postgres-data: