version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
