# Generated by Django 5.2.4 on 2025-08-07 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('plc', 'PLC'), ('llc', 'LLC'), ('inc', 'INC'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('legal_entity_identifier', models.CharField(blank=True, null=True, verbose_name='LEI (ISO 17442)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_of_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnchainVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_hash', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('onchain_id', models.IntegerField(blank=True, null=True)),
                ('onchain_status', models.CharField(choices=[('register', 'Register'), ('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='register', max_length=20)),
                ('context', models.JSONField()),
                ('proposer_wallet', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_verifications', to='organizations.organization')),
            ],
            options={
                'db_table': 'onchain_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_users',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
