# Generated by Django 5.2.4 on 2025-08-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
    ]
