# Generated by Django 5.2.4 on 2025-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20250807_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onchainverification',
            name='trx_hash',
            field=models.CharField(default='0x0000000000000000000000000000000000000000000000000000000000000000', max_length=66, unique=True),
            preserve_default=False,
        ),
    ]
