# Generated by Django 5.2.4 on 2025-09-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0003_alter_onchainverification_trx_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationuser',
            options={'ordering': ['-created_at'], 'permissions': [('approve_organization', 'Can approve organization'), ('reject_organization', 'Can reject organization'), ('ban_organization', 'Can ban organization'), ('manage_organization_users', 'Can manage organization users'), ('view_organization_admin', 'Can view as organization admin'), ('create_proposal', 'Can create proposals'), ('approve_proposal', 'Can approve proposals'), ('vote_on_proposal', 'Can vote on proposals'), ('execute_proposal', 'Can execute proposals'), ('cancel_proposal', 'Can cancel proposals')]},
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
