# Generated by Django 5.2.4 on 2025-10-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onchainverification',
            name='onchain_status',
            field=models.CharField(choices=[('register', 'Register'), ('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
