// DBML export for audit-trail-service

Table "transactions" {
  "created_at" timestamp
  "updated_at" timestamp
  "confirmation_source" varchar [null]
  "id" int [pk]
  "trx_status" varchar
  "trx_metadata" varchar [null]
  "trx_hash" varchar
}

