// DBML export for dao-service

Table "Proposal" {
  "updated_at" timestamp
  "proposal_onchain_id" int [null]
  "proposal_type" varchar
  "audit_id" int [null]
  "trx_status" int
  "created_at" timestamp
  "id" int [pk]
  "proposal_status" varchar
  "metadata" varchar [null]
  "proposer_address" varchar
  "processed_by" varchar [null]
  "trx_hash" varchar
}

