// DBML export for user-management

Table "mfs_businesses" {
  "id" int [pk]
  "is_approved" boolean
  "proposal_onchain_id" int [null]
  "membership_onchain_status" varchar [null]
  "created_at" timestamp
  "updated_at" timestamp
  "trx_hash" varchar [null]
  "wallet_address" varchar [null]
  "native_currency" varchar
  "certificate" varchar [null]
  "name" varchar
  "email" varchar
  "context" varchar
  "type" varchar
  "location" varchar
}

Table "users" {
  "exchangeUserId" int [ref, null]
  "updated_at" timestamp
  "mfsBusinessId" int [ref, null]
  "id" int [pk]
  "role" varchar
  "created_at" timestamp
  "name" varchar
  "email" varchar
  "password" varchar
}

Table "exchange_users" {
  "id" int [pk]
  "balance" double
  "created_at" timestamp
  "updated_at" timestamp
  "name" varchar
  "email" varchar
}

