# Generated by Django 5.2.4 on 2025-08-07 10:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', unique=True, verbose_name='Phone Number'),
        ),
    ]
