services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - fincube23_network

    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_MANAGEMENT_CORS_ALLOW_ORIGINS: "*"
      RABBITMQ_MANAGEMENT_CORS_MAX_AGE: 3600
      RABBITMQ_LOGS: "-"
      RABBITMQ_SASL_LOGS: "-"


networks:
  fincube23_network:
    external: true


