# Allow guest user to connect from any host (for development only)
loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json

# Management plugin CORS settings

management.cors.allow_origins.1 = *
management.cors.max_age = 3600
management.cors.allow_credentials = true
management.cors.allow_methods.1 = GET
management.cors.allow_methods.2 = POST
management.cors.allow_methods.3 = PUT
management.cors.allow_methods.4 = DELETE
management.cors.allow_methods.5 = HEAD
management.cors.allow_methods.6 = OPTIONS
management.cors.allow_headers.1 = authorization
management.cors.allow_headers.2 = content-type
management.cors.allow_headers.3 = content-length

# Enable management plugin HTTP API

